version: "2"

services:
  nginx:
    image: nginx:alpine
    restart: always
    links:
      - 5.4.36-fpm
      - 5.6.30-fpm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/enabled:/etc/nginx/conf.d
      - ./nginx/snippets:/nginx/snippets
      - ./nginx/certificates:/nginx/certificates
    volumes_from:
      - data

  5.4.36-fpm:
    image: php:5.4.36-fpm
    restart: always
    volumes_from:
      - data

  5.6.30-fpm:
    image: php:5.6.30-fpm
    restart: always
    volumes_from:
      - data

  mariadb:
    image: mariadb:10.5.8 #v10.5.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/storage:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root # Remove line for production
      PMA_PASSWORD: root # Remove line for production
    depends_on:
      - mariadb
    # ports:
    #   - "8080:80"

  data:
    image: alpine:latest
    command: echo "--- Docker data volume READY."
    volumes:
      - ./vhosts:/vhosts
      - ./tmp:/tmp
